### ISSUE TITLE
Subsonic is no longer open source

### ISSUE THREAD

**Issue by ola-** [Kickball/awesome-selfhosted#559] opened 2016-05-27 20:42 UTC
[according to the author](http://forum.subsonic.org/forum/viewtopic.php?f=4&t=16604#p71128).

Replace listing with [libresonic](https://github.com/Libresonic/libresonic)?

**Comment by alexfornuto** [comment] 2016-05-28 07:25
https://github.com/Kickball/awesome-selfhosted/pull/550

**Comment by Kickball** [comment] 2016-05-31 20:13
Closed as duplicate of #550.

**Closed by Kickball** 2016-05-31 20:13 UTC
Labels: duplicate
